### ISSUE TITLE
Update Lifecycle-Hooks

### ISSUE THREAD

**Issue by GenesisTMS** [angulardart-community/site-angulardart#41]
Would like to update Lifecycle page.

## Todo

- [x] Deprecate OnChanges to AfterChangse
(https://github.com/angulardart-community/site-angulardart/pull/40)
- [x] Migrate examples to latest angular
- [x] Change image hooks-in-sequence.png
- [x] Recreate gif for `AfterChanges` example.
(https://github.com/angulardart-community/site-angulardart/pull/44)

_... please comment what changes you would like ..._

## Ideas

- More obvious examples. Better visualization of gifs -> add colors, etc.
- Make more visible where is the line where host view can be modified. (eg, in image of _hooks-in-sequence.png_)
- Better explain why `DoCheck` is called so many times. What _change detection cycle_ means.

This can be confusing to users:
> Detect and act upon changes that Angular can’t or won’t detect on its own

What are these _undetectable_ changes.

- Mention `ChangeDetectionStrategy`.
- Or create follow up article only about _change detector_ and what means when component is dirty.
  (some examples are in `markForCheck` and `markChildForCheck` reference pages.)

**Comment by insinfo** [comment]
@GenesisTMS
I think it's really good to talk about "ChangeDetectionStrategy" because there is little documentation about it.
And I think it's very important to also talk about creating custom UI components, with examples of Button components, Selects, Custom Inputs etc, this would help many newbie developers, I had to learn about it by analyzing the source code of many components made in Angular TypeScript or even done with old versions of AngularDart, it was quite difficult.

**Comment by GenesisTMS** [comment]
@GZGavinZhao This issue can be closed. I will eventually create issues based on additional ideas.
